name = "h2oatlas-analytics"
main = "src/index.ts"
compatibility_date = "2024-09-01"
workers_dev = true

routes = [
  { pattern = "analytics.h2oatlas.ee", custom_domain = true }
]

[vars]
ANALYTICS_ALLOW_ORIGIN = "https://h2oatlas.ee"

[[kv_namespaces]]
binding = "ANALYTICS_KV"
id = "b956856d9ca045e1a2cc58fb51598165"
preview_id = "2929154b206b4da89bf2809c1045608a"
