"use client";

import type { DashboardLang } from "./dashboard-types";
import type { FrontendPlace } from "./types";
import type { DashboardTopChromeProps } from "./dashboard-controller-component-props";

export type TopChromeInput = {
  lang: DashboardLang;
  t: DashboardTopChromeProps["t"];
  isMobile: boolean;
  drawerOpen: boolean;
  headerCompact: boolean;
  showLangDialog: boolean;
  langMenuOpen: boolean;
  sidebarCollapsed: boolean;
  nearbyOnly: boolean;
  nearbyRadiusKm: DashboardTopChromeProps["nearbyRadiusKm"];
  userCoords: DashboardTopChromeProps["userCoords"];
  geoError: string | null;
  query: string;
  cyrillicFont: DashboardTopChromeProps["cyrillicFont"];
  segment: string;
  alertsOnly: boolean;
  county: string;
  risk: string;
  official: DashboardTopChromeProps["official"];
  minProb: number;
  minProbInput: DashboardTopChromeProps["minProbInput"];
  sampleDateFrom: string;
  sampleDateTo: string;
  filteredCount: number;
  mapAlertsCount: number;
  mapNearMeCount: DashboardTopChromeProps["mapNearMeCount"];
  highRiskCount: number;
  violationsCount: number;
  healthIndex: number;
  domainCounts: DashboardTopChromeProps["domainCounts"];
  placeKinds: DashboardTopChromeProps["placeKinds"];
  counties: DashboardTopChromeProps["counties"];
  watchlistPlaces: FrontendPlace[];
  onCloseDrawer: () => void;
  onOpenAboutModel: () => void;
  onChooseLang: DashboardTopChromeProps["onChooseLang"];
  onToggleLangMenu: () => void;
  onSelectLangOption: DashboardTopChromeProps["onSelectLangOption"];
  onOpenFilters: () => void;
  onSetQuery: (value: string) => void;
  onActivateNearMe: () => void;
  onOpenInfo: () => void;
  onSetSegment: (value: string) => void;
  onToggleAlertsOnly: () => void;
  onToggleNearbyOnly: () => void;
  onClearRisk: () => void;
  onClearFilters: () => void;
  onShowCountBubble: (text: string) => void;
  onClearGeoError: () => void;
  onToggleSidebar: () => void;
  onSetNearbyRadiusKm: (value: number) => void;
  onClearNearMe: () => void;
  onSetLang: DashboardTopChromeProps["onSetLang"];
  onPushHeaderLang: DashboardTopChromeProps["onPushHeaderLang"];
  onSetCyrillicFont: DashboardTopChromeProps["onSetCyrillicFont"];
  onSetCounty: (value: string) => void;
  onSetRisk: (value: string) => void;
  onSetOfficial: DashboardTopChromeProps["onSetOfficial"];
  onSetMinProbInput: DashboardTopChromeProps["onSetMinProbInput"];
  onSetSampleDateFrom: (value: string) => void;
  onSetSampleDateTo: (value: string) => void;
  onSelectPoint: (id: string) => void;
  placeKindLabel: DashboardTopChromeProps["placeKindLabel"];
  riskLabel: DashboardTopChromeProps["riskLabel"];
  officialLabel: DashboardTopChromeProps["officialLabel"];
};
