"use client";

import type { DashboardLang } from "./dashboard-types";
import type { FrontendPlace, FrontendSnapshot } from "./types";
import type { DashboardMainContentProps } from "./dashboard-controller-component-props";

export type MainContentInput = {
  lang: DashboardLang;
  snapshot: FrontendSnapshot;
  isMapFullscreen: boolean;
  isMobile: boolean;
  chipPos: DashboardMainContentProps["chipPos"];
  segment: string;
  alertsOnly: boolean;
  nearbyOnly: boolean;
  risk: string;
  county: string;
  official: DashboardMainContentProps["official"];
  minProb: number;
  minProbInput: DashboardMainContentProps["minProbInput"];
  sampleDateFrom: string;
  sampleDateTo: string;
  nearbyRadiusKm: number;
  userCoords: DashboardMainContentProps["userCoords"];
  geoError: string | null;
  theme: DashboardMainContentProps["theme"];
  selectedId: string | null;
  selectedPlace: FrontendPlace | null;
  clusterPlaces: FrontendPlace[] | null;
  watchlist: string[];
  measurementsOpen: boolean;
  historyOpen: boolean;
  mobilePanelState: DashboardMainContentProps["mobilePanelState"];
  sheetMode: DashboardMainContentProps["sheetMode"];
  sheetDragging: boolean;
  sheetDragOffset: number;
  filteredCount: number;
  highCount: number;
  lowCount: number;
  violationsCount: number;
  mobileBottomOverlayPx: number;
  counties: DashboardMainContentProps["counties"];
  countyGeoJson: DashboardMainContentProps["countyGeoJson"];
  fitBoundsKey: string;
  mapPlaces: FrontendPlace[];
  fitBoundsPlaces: DashboardMainContentProps["fitBoundsPlaces"];
  placesTableRows: DashboardMainContentProps["placesTableRows"];
  placesTableSort: DashboardMainContentProps["placesTableSort"];
  topAlerts: DashboardMainContentProps["topAlerts"];
  domainStats: DashboardMainContentProps["domainStats"];
  dataFetchedLabel: string | null;
  modelTrainedLabel: string | null;
  dataFreshnessLevel: DashboardMainContentProps["dataFreshnessLevel"];
  modelFreshnessLevel: DashboardMainContentProps["modelFreshnessLevel"];
  freshnessLabel: DashboardMainContentProps["freshnessLabel"];
  title: string;
  filtersLabel: string;
  clearFiltersLabel: string;
  nearMeLabel: string;
  selectedPointTitle: string;
  emptySelectedPointHint: string;
  measurementsLabel: string;
  historyLabel: string;
  historyPlaceholder: string;
  closeLabel: string;
  countyLabel: string;
  riskLabelText: string;
  officialLabelText: string;
  minProbLabel: string;
  latestSampleDateLabel: string;
  dateFromLabel: string;
  dateToLabel: string;
  resetDateLabel: string;
  latestSampleDateHint: string;
  nearRadiusLabel: string;
  clearNearMeLabel: string;
  placeKindLabel: DashboardMainContentProps["placeKindLabel"];
  countyPretty: DashboardMainContentProps["countyPretty"];
  officialStatusText: DashboardMainContentProps["officialStatusText"];
  explainViolation: DashboardMainContentProps["explainViolation"];
  explainMeasurementNorm: DashboardMainContentProps["explainMeasurementNorm"];
  explainHistoryMeasurements: DashboardMainContentProps["explainHistoryMeasurements"];
  explainViolationFromHistory: DashboardMainContentProps["explainViolationFromHistory"];
  labelForParam: DashboardMainContentProps["labelForParam"];
  descForParam: DashboardMainContentProps["descForParam"];
  openInfo: DashboardMainContentProps["openInfo"];
  onSelectPoint: (id: string) => void;
  onSelectCluster: DashboardMainContentProps["onSelectCluster"];
  onSelectCounty: (county: string) => void;
  onToggleWatch: (id: string) => void;
  onCycleSort: DashboardMainContentProps["onCycleSort"];
  onToggleMeasurements: () => void;
  onToggleHistory: () => void;
  onSetCounty: (value: string) => void;
  onSetRisk: DashboardMainContentProps["onSetRisk"];
  onSetOfficial: DashboardMainContentProps["onSetOfficial"];
  onSetMinProbInput: DashboardMainContentProps["onSetMinProbInput"];
  onSetSampleDateFrom: (value: string) => void;
  onSetSampleDateTo: (value: string) => void;
  onSetNearbyRadiusKm: (value: number) => void;
  onSetTheme: DashboardMainContentProps["onSetTheme"];
  onSetLang: DashboardMainContentProps["onSetLang"];
  onToggleFullscreen: DashboardMainContentProps["onToggleFullscreen"];
  onActivateNearMe: () => void;
  onSelectAllSegment: () => void;
  onToggleSegment: DashboardMainContentProps["onToggleSegment"];
  onToggleAlerts: () => void;
  onToggleNearMe: () => void;
  onClearRisk: () => void;
  onClearFilters: () => void;
  onCyclePanelState: () => void;
  onSheetPointerDown: DashboardMainContentProps["onSheetPointerDown"];
  onSheetPointerMove: DashboardMainContentProps["onSheetPointerMove"];
  onSheetPointerUp: DashboardMainContentProps["onSheetPointerUp"];
  onSheetPointerCancel: DashboardMainContentProps["onSheetPointerCancel"];
  onCloseFilterMode: () => void;
  onClosePlaceMode: () => void;
  onClearSampleDates: () => void;
  onClearNearMe: () => void;
  onChipPointerDown: DashboardMainContentProps["onChipPointerDown"];
  onChipPointerMove: DashboardMainContentProps["onChipPointerMove"];
  onChipPointerUp: DashboardMainContentProps["onChipPointerUp"];
  onChipClickCapture: DashboardMainContentProps["onChipClickCapture"];
};
