"use client";

import type { ComponentProps } from "react";
import type DashboardDesktopSelectedPlacePanel from "../components/DashboardDesktopSelectedPlacePanel";
import type DashboardMobileBottomSheet from "../components/DashboardMobileBottomSheet";
import type { DashboardFreshnessLevel, DashboardLang } from "./dashboard-types";
import type { FrontendPlace, FrontendSnapshot } from "./types";

type MobileBottomSheetProps = ComponentProps<typeof DashboardMobileBottomSheet>;
type DesktopPanelProps = ComponentProps<typeof DashboardDesktopSelectedPlacePanel>;

type DashboardOfficialFilter = MobileBottomSheetProps["official"];
type DashboardTheme = MobileBottomSheetProps["theme"];

export type DashboardSelectedPlaceWorkspaceComponentProps = {
  desktopDetailRef: ComponentProps<typeof DashboardDesktopSelectedPlacePanel>["ref"];
  lang: DashboardLang;
  snapshot: FrontendSnapshot;
  selectedPlace: FrontendPlace | null;
  clusterPlaces: FrontendPlace[] | null;
  watchlist: string[];
  measurementsOpen: boolean;
  historyOpen: boolean;
  historyPlaceholder: string;
  selectedPointTitle: string;
  emptySelectedPointHint: string;
  measurementsLabel: string;
  historyLabel: string;
  closeLabel: string;
  clearFiltersLabel: string;
  countyLabel: string;
  riskLabelText: string;
  officialLabelText: string;
  minProbLabel: string;
  latestSampleDateLabel: string;
  dateFromLabel: string;
  dateToLabel: string;
  resetDateLabel: string;
  latestSampleDateHint: string;
  nearRadiusLabel: string;
  clearNearMeLabel: string;
  themeLightLabel: string;
  themeDarkLabel: string;
  filteredCount: number;
  dataFetchedLabel: string | null;
  modelTrainedLabel: string | null;
  dataFreshnessLevel: DashboardFreshnessLevel;
  modelFreshnessLevel: DashboardFreshnessLevel;
  freshnessLabel: (level: DashboardFreshnessLevel) => string;
  highCount: number;
  lowCount: number;
  violationsCount: number;
  riskOrder: string[];
  officialOrder: ReadonlyArray<"all" | "compliant" | "violation" | "unknown">;
  county: string;
  risk: string;
  official: DashboardOfficialFilter;
  minProb: number;
  minProbInput: number;
  sampleDateFrom: string;
  sampleDateTo: string;
  nearbyOnly: boolean;
  nearbyRadiusKm: number;
  userCoords: { lat: number; lon: number } | null;
  geoError: string | null;
  counties: Array<{ value: string; label: string }>;
  theme: DashboardTheme;
  mobilePanelState: MobileBottomSheetProps["mobilePanelState"];
  sheetMode: MobileBottomSheetProps["sheetMode"];
  sheetDragging: boolean;
  sheetDragOffset: number;
  placeKindLabel: (kind: string) => string;
  countyPretty: DesktopPanelProps["countyPretty"];
  officialStatusText: DesktopPanelProps["officialStatusText"];
  explainViolation: DesktopPanelProps["explainViolation"];
  explainMeasurementNorm: DesktopPanelProps["explainMeasurementNorm"];
  explainHistoryMeasurements: DesktopPanelProps["explainHistoryMeasurements"];
  explainViolationFromHistory: DesktopPanelProps["explainViolationFromHistory"];
  labelForParam: DesktopPanelProps["labelForParam"];
  descForParam: DesktopPanelProps["descForParam"];
  openInfo: (title: string, text: string) => void;
  onSelectPoint: (id: string) => void;
  onToggleWatch: (id: string) => void;
  onToggleMeasurements: () => void;
  onToggleHistory: () => void;
  onCyclePanelState: () => void;
  onSheetPointerDown: MobileBottomSheetProps["onSheetPointerDown"];
  onSheetPointerMove: MobileBottomSheetProps["onSheetPointerMove"];
  onSheetPointerUp: MobileBottomSheetProps["onSheetPointerUp"];
  onSheetPointerCancel: MobileBottomSheetProps["onSheetPointerCancel"];
  onClearFilters: () => void;
  onCloseFilterMode: () => void;
  onClosePlaceMode: () => void;
  onSetCounty: (value: string) => void;
  onSetRisk: MobileBottomSheetProps["onSetRisk"];
  onSetOfficial: MobileBottomSheetProps["onSetOfficial"];
  onSetMinProbInput: MobileBottomSheetProps["onSetMinProbInput"];
  onSetSampleDateFrom: (value: string) => void;
  onSetSampleDateTo: (value: string) => void;
  onClearSampleDates: () => void;
  onSetNearbyRadiusKm: (value: number) => void;
  onClearNearMe: () => void;
  onSetTheme: MobileBottomSheetProps["onSetTheme"];
  onSetLang: (lang: DashboardLang) => void;
};
