"use client";

import type { DashboardBootstrapState, DashboardRuntimeState } from "./dashboard-controller-input-types";

export function buildTopChromeInput(state: DashboardBootstrapState, runtime: DashboardRuntimeState) {
  return {
    lang: state.lang,
    t: state.t,
    isMobile: runtime.isMobile,
    drawerOpen: state.drawerOpen,
    headerCompact: state.headerCompact,
    showLangDialog: state.showLangDialog,
    langMenuOpen: state.langMenuOpen,
    sidebarCollapsed: state.sidebarCollapsed,
    nearbyOnly: state.nearbyOnly,
    nearbyRadiusKm: state.nearbyRadiusKm,
    userCoords: state.userCoords,
    geoError: state.geoError,
    query: state.query,
    cyrillicFont: state.cyrillicFont,
    segment: state.segment,
    alertsOnly: state.alertsOnly,
    county: state.county,
    risk: state.risk,
    official: state.official,
    minProb: state.minProb,
    minProbInput: state.minProbInput,
    sampleDateFrom: state.sampleDateFrom,
    sampleDateTo: state.sampleDateTo,
    filteredCount: runtime.filtered.length,
    mapAlertsCount: runtime.mapAlertsCount,
    mapNearMeCount: runtime.mapNearMeCount,
    highRiskCount: runtime.high,
    violationsCount: runtime.violations,
    healthIndex: runtime.healthIndex,
    domainCounts: runtime.domainCounts,
    placeKinds: runtime.placeKinds,
    counties: runtime.counties,
    watchlistPlaces: runtime.watchlistPlaces,
    onCloseDrawer: () => state.setDrawerOpen(false),
    onOpenAboutModel: runtime.openAboutModel,
    onChooseLang: runtime.chooseLang,
    onToggleLangMenu: runtime.toggleLangMenu,
    onSelectLangOption: runtime.selectLangOption,
    onOpenFilters: runtime.openFilters,
    onSetQuery: state.setQuery,
    onActivateNearMe: runtime.activateNearMe,
    onOpenInfo: runtime.openAboutService,
    onSetSegment: state.setSegment,
    onToggleAlertsOnly: () => state.setAlertsOnly((value) => !value),
    onToggleNearbyOnly: runtime.toggleNearbyOnly,
    onClearRisk: () => state.setRisk("all"),
    onClearFilters: runtime.clearFilters,
    onShowCountBubble: runtime.showCountBubble,
    onClearGeoError: runtime.clearGeoError,
    onToggleSidebar: runtime.toggleSidebar,
    onSetNearbyRadiusKm: state.setNearbyRadiusKm,
    onClearNearMe: runtime.clearNearMe,
    onSetLang: state.setLang,
    onPushHeaderLang: runtime.pushHeaderLang,
    onSetCyrillicFont: state.setCyrillicFont,
    onSetCounty: state.setCounty,
    onSetRisk: state.setRisk,
    onSetOfficial: state.setOfficial,
    onSetMinProbInput: state.setMinProbInput,
    onSetSampleDateFrom: state.setSampleDateFrom,
    onSetSampleDateTo: state.setSampleDateTo,
    onSelectPoint: runtime.selectPoint,
    placeKindLabel: runtime.placeKindLabel,
    riskLabel: runtime.riskLabel,
    officialLabel: runtime.officialLabel,
  };
}
