"use client";

import type { ComponentProps } from "react";
import type DashboardDesktopSelectedPlacePanel from "../components/DashboardDesktopSelectedPlacePanel";
import type DashboardMobileBottomSheet from "../components/DashboardMobileBottomSheet";
import DashboardIcon, { type DashboardIconName } from "../components/DashboardIcon";
import { fmtDate, lruet } from "./dashboard-utils";
import type { DashboardSelectedPlaceWorkspaceComponentProps } from "./dashboard-selected-place-workspace-component-types";
import { assessNorm } from "./water-rules";

type DesktopPanelProps = ComponentProps<typeof DashboardDesktopSelectedPlacePanel>;
type MobileBottomSheetProps = ComponentProps<typeof DashboardMobileBottomSheet>;

export function buildDashboardDesktopSelectedPlacePanelProps(
  props: DashboardSelectedPlaceWorkspaceComponentProps,
): DesktopPanelProps {
  const {
    desktopDetailRef,
    lang,
    snapshot,
    selectedPlace,
    clusterPlaces,
    watchlist,
    measurementsOpen,
    historyOpen,
    historyPlaceholder,
    selectedPointTitle,
    emptySelectedPointHint,
    onSelectPoint,
    onToggleWatch,
    onToggleMeasurements,
    onToggleHistory,
    countyPretty,
    officialStatusText,
    explainViolation,
    openInfo,
    labelForParam,
    descForParam,
    explainMeasurementNorm,
    explainHistoryMeasurements,
    explainViolationFromHistory,
  } = props;

  return {
    ref: desktopDetailRef,
    lang,
    snapshot,
    selectedPlace,
    clusterPlaces,
    watchlist,
    measurementsOpen,
    historyOpen,
    historyPlaceholder,
    title: selectedPointTitle,
    emptyHint: emptySelectedPointHint,
    onSelectPoint,
    onToggleWatch,
    onToggleMeasurements,
    onToggleHistory,
    countyPretty,
    fmtDate,
    officialStatusText,
    explainViolation,
    openInfo,
    labelForParam,
    descForParam,
    explainMeasurementNorm,
    explainHistoryMeasurements,
    explainViolationFromHistory,
    renderStarIcon: (active) => (
      <span className="cellIcon" style={{ color: active ? "#f59e0b" : "var(--muted)" }}>
        <DashboardIcon name={active ? "star" : "star-outline"} />
      </span>
    ),
    watchlistAddLabel: lruet(lang, "Добавить в избранное", "Lisa jälgimisse", "Add to watchlist"),
    watchlistRemoveLabel: lruet(lang, "Убрать из избранного", "Eemalda jälgimisest", "Remove from watchlist"),
  };
}

export function buildDashboardMobileBottomSheetProps(
  props: DashboardSelectedPlaceWorkspaceComponentProps,
): MobileBottomSheetProps {
  const {
    lang,
    mobilePanelState,
    sheetMode,
    sheetDragging,
    sheetDragOffset,
    filteredCount,
    selectedPlace,
    clusterPlaces,
    watchlist,
    measurementsOpen,
    historyOpen,
    measurementsLabel,
    historyLabel,
    historyPlaceholder,
    closeLabel,
    clearFiltersLabel,
    countyLabel,
    riskLabelText,
    officialLabelText,
    minProbLabel,
    latestSampleDateLabel,
    dateFromLabel,
    dateToLabel,
    resetDateLabel,
    latestSampleDateHint,
    nearRadiusLabel,
    clearNearMeLabel,
    themeLightLabel,
    themeDarkLabel,
    highCount,
    lowCount,
    violationsCount,
    riskOrder,
    officialOrder,
    county,
    risk,
    official,
    minProb,
    minProbInput,
    sampleDateFrom,
    sampleDateTo,
    nearbyOnly,
    nearbyRadiusKm,
    userCoords,
    geoError,
    counties,
    theme,
    placeKindLabel,
    countyPretty,
    officialStatusText,
    explainViolation,
    openInfo,
    onToggleWatch,
    onToggleMeasurements,
    onToggleHistory,
    labelForParam,
    descForParam,
    explainMeasurementNorm,
    explainHistoryMeasurements,
    explainViolationFromHistory,
    onCyclePanelState,
    onSheetPointerDown,
    onSheetPointerMove,
    onSheetPointerUp,
    onSheetPointerCancel,
    onClearFilters,
    onCloseFilterMode,
    onClosePlaceMode,
    onSelectPoint,
    onSetCounty,
    onSetRisk,
    onSetOfficial,
    onSetMinProbInput,
    onSetSampleDateFrom,
    onSetSampleDateTo,
    onClearSampleDates,
    onSetNearbyRadiusKm,
    onClearNearMe,
    onSetTheme,
    onSetLang,
  } = props;

  return {
    lang,
    mobilePanelState,
    sheetMode,
    sheetDragging,
    sheetDragOffset,
    filteredCount,
    selectedPlace,
    clusterPlaces,
    watchlist,
    measurementsOpen,
    historyOpen,
    measurementsLabel,
    historyLabel,
    historyPlaceholder,
    closeLabel,
    clearFiltersLabel,
    countyLabel,
    riskLabel: riskLabelText,
    officialLabel: officialLabelText,
    minProbLabel,
    latestSampleDateLabel,
    dateFromLabel,
    dateToLabel,
    resetDateLabel,
    latestSampleDateHint,
    nearRadiusLabel,
    clearNearMeLabel,
    themeLightLabel,
    themeDarkLabel,
    visibleCount: filteredCount,
    highCount,
    lowCount,
    violationsCount,
    riskOrder,
    officialOrder,
    county,
    risk,
    official,
    minProb,
    minProbInput,
    sampleDateFrom,
    sampleDateTo,
    nearbyOnly,
    nearbyRadiusKm,
    userCoords,
    geoError,
    counties,
    theme,
    placeKindLabel,
    countyPretty,
    fmtDate,
    officialStatusText,
    explainViolation,
    openInfo,
    toggleWatch: onToggleWatch,
    onToggleMeasurements,
    onToggleHistory,
    labelForParam,
    descForParam,
    explainMeasurementNorm,
    explainHistoryMeasurements,
    explainViolationFromHistory,
    assessNorm,
    onCyclePanelState,
    onSheetPointerDown,
    onSheetPointerMove,
    onSheetPointerUp,
    onSheetPointerCancel,
    onClearFilters,
    onCloseFilterMode,
    onClosePlaceMode,
    onSelectPoint,
    onSetCounty,
    onSetRisk,
    onSetOfficial,
    onSetMinProbInput,
    onSetSampleDateFrom,
    onSetSampleDateTo,
    onClearSampleDates,
    onSetNearbyRadiusKm,
    onClearNearMe,
    onSetTheme,
    onSetLang,
    renderIcon: (name) => <DashboardIcon name={name as DashboardIconName} />,
  };
}
