"use client";

import type { ComponentProps } from "react";
import type DashboardMapCanvas from "../components/DashboardMapCanvas";
import type DashboardSelectedPlaceWorkspace from "../components/DashboardSelectedPlaceWorkspace";
import type { DashboardLang } from "./dashboard-types";
import type { FrontendPlace, FrontendSnapshot } from "./types";

type MapCanvasProps = ComponentProps<typeof DashboardMapCanvas>;
type SelectedPlaceWorkspaceProps = ComponentProps<typeof DashboardSelectedPlaceWorkspace>;

export type DashboardMapWorkspaceComponentProps = {
  lang: DashboardLang;
  snapshot: FrontendSnapshot;
  mapPanelRef: MapCanvasProps["mapPanelRef"];
  desktopDetailRef: SelectedPlaceWorkspaceProps["desktopDetailRef"];
  chipBarRef: MapCanvasProps["chipBarRef"];
  isMapFullscreen: MapCanvasProps["isMapFullscreen"];
  isMobile: MapCanvasProps["isMobile"];
  chipPos: MapCanvasProps["chipPos"];
  segment: MapCanvasProps["segment"];
  alertsOnly: MapCanvasProps["alertsOnly"];
  nearbyOnly: SelectedPlaceWorkspaceProps["nearbyOnly"];
  risk: SelectedPlaceWorkspaceProps["risk"];
  county: SelectedPlaceWorkspaceProps["county"];
  official: SelectedPlaceWorkspaceProps["official"];
  minProb: SelectedPlaceWorkspaceProps["minProb"];
  minProbInput: SelectedPlaceWorkspaceProps["minProbInput"];
  sampleDateFrom: SelectedPlaceWorkspaceProps["sampleDateFrom"];
  sampleDateTo: SelectedPlaceWorkspaceProps["sampleDateTo"];
  nearbyRadiusKm: SelectedPlaceWorkspaceProps["nearbyRadiusKm"];
  userCoords: MapCanvasProps["userCoords"];
  geoError: SelectedPlaceWorkspaceProps["geoError"];
  theme: SelectedPlaceWorkspaceProps["theme"];
  selectedPlace: MapCanvasProps["selectedPlace"];
  clusterPlaces: FrontendPlace[] | null;
  watchlist: string[];
  measurementsOpen: SelectedPlaceWorkspaceProps["measurementsOpen"];
  historyOpen: SelectedPlaceWorkspaceProps["historyOpen"];
  mobilePanelState: SelectedPlaceWorkspaceProps["mobilePanelState"];
  sheetMode: SelectedPlaceWorkspaceProps["sheetMode"];
  sheetDragging: SelectedPlaceWorkspaceProps["sheetDragging"];
  sheetDragOffset: SelectedPlaceWorkspaceProps["sheetDragOffset"];
  filteredCount: SelectedPlaceWorkspaceProps["filteredCount"];
  highCount: SelectedPlaceWorkspaceProps["highCount"];
  lowCount: SelectedPlaceWorkspaceProps["lowCount"];
  violationsCount: SelectedPlaceWorkspaceProps["violationsCount"];
  mobileBottomOverlayPx: MapCanvasProps["mobileBottomOverlayPx"];
  counties: SelectedPlaceWorkspaceProps["counties"];
  countyGeoJson: MapCanvasProps["countyGeoJson"];
  fitBoundsKey: MapCanvasProps["fitBoundsKey"];
  mapPlaces: MapCanvasProps["mapPlaces"];
  fitBoundsPlaces: MapCanvasProps["fitBoundsPlaces"];
  dataFetchedLabel: SelectedPlaceWorkspaceProps["dataFetchedLabel"];
  modelTrainedLabel: SelectedPlaceWorkspaceProps["modelTrainedLabel"];
  dataFreshnessLevel: SelectedPlaceWorkspaceProps["dataFreshnessLevel"];
  modelFreshnessLevel: SelectedPlaceWorkspaceProps["modelFreshnessLevel"];
  freshnessLabel: SelectedPlaceWorkspaceProps["freshnessLabel"];
  title: MapCanvasProps["title"];
  filtersLabel: MapCanvasProps["filtersLabel"];
  clearFiltersLabel: SelectedPlaceWorkspaceProps["clearFiltersLabel"];
  nearMeLabel: MapCanvasProps["nearMeLabel"];
  selectedPointTitle: SelectedPlaceWorkspaceProps["selectedPointTitle"];
  emptySelectedPointHint: SelectedPlaceWorkspaceProps["emptySelectedPointHint"];
  measurementsLabel: SelectedPlaceWorkspaceProps["measurementsLabel"];
  historyLabel: SelectedPlaceWorkspaceProps["historyLabel"];
  historyPlaceholder: SelectedPlaceWorkspaceProps["historyPlaceholder"];
  closeLabel: SelectedPlaceWorkspaceProps["closeLabel"];
  countyLabel: SelectedPlaceWorkspaceProps["countyLabel"];
  riskLabelText: SelectedPlaceWorkspaceProps["riskLabelText"];
  officialLabelText: SelectedPlaceWorkspaceProps["officialLabelText"];
  minProbLabel: SelectedPlaceWorkspaceProps["minProbLabel"];
  latestSampleDateLabel: SelectedPlaceWorkspaceProps["latestSampleDateLabel"];
  dateFromLabel: SelectedPlaceWorkspaceProps["dateFromLabel"];
  dateToLabel: SelectedPlaceWorkspaceProps["dateToLabel"];
  resetDateLabel: SelectedPlaceWorkspaceProps["resetDateLabel"];
  latestSampleDateHint: SelectedPlaceWorkspaceProps["latestSampleDateHint"];
  nearRadiusLabel: SelectedPlaceWorkspaceProps["nearRadiusLabel"];
  clearNearMeLabel: SelectedPlaceWorkspaceProps["clearNearMeLabel"];
  placeKindLabel: SelectedPlaceWorkspaceProps["placeKindLabel"];
  countyPretty: SelectedPlaceWorkspaceProps["countyPretty"];
  officialStatusText: SelectedPlaceWorkspaceProps["officialStatusText"];
  explainViolation: SelectedPlaceWorkspaceProps["explainViolation"];
  explainMeasurementNorm: SelectedPlaceWorkspaceProps["explainMeasurementNorm"];
  explainHistoryMeasurements: SelectedPlaceWorkspaceProps["explainHistoryMeasurements"];
  explainViolationFromHistory: SelectedPlaceWorkspaceProps["explainViolationFromHistory"];
  labelForParam: SelectedPlaceWorkspaceProps["labelForParam"];
  descForParam: SelectedPlaceWorkspaceProps["descForParam"];
  openInfo: SelectedPlaceWorkspaceProps["openInfo"];
  onSelectPoint: (id: string) => void;
  onSelectCluster: MapCanvasProps["onSelectCluster"];
  onSelectCounty: MapCanvasProps["onSelectCounty"];
  onToggleWatch: SelectedPlaceWorkspaceProps["onToggleWatch"];
  onToggleMeasurements: SelectedPlaceWorkspaceProps["onToggleMeasurements"];
  onToggleHistory: SelectedPlaceWorkspaceProps["onToggleHistory"];
  onSetCounty: SelectedPlaceWorkspaceProps["onSetCounty"];
  onSetRisk: SelectedPlaceWorkspaceProps["onSetRisk"];
  onSetOfficial: SelectedPlaceWorkspaceProps["onSetOfficial"];
  onSetMinProbInput: SelectedPlaceWorkspaceProps["onSetMinProbInput"];
  onSetSampleDateFrom: SelectedPlaceWorkspaceProps["onSetSampleDateFrom"];
  onSetSampleDateTo: SelectedPlaceWorkspaceProps["onSetSampleDateTo"];
  onSetNearbyRadiusKm: SelectedPlaceWorkspaceProps["onSetNearbyRadiusKm"];
  onSetTheme: SelectedPlaceWorkspaceProps["onSetTheme"];
  onSetLang: SelectedPlaceWorkspaceProps["onSetLang"];
  onToggleFullscreen: MapCanvasProps["onToggleFullscreen"];
  onActivateNearMe: MapCanvasProps["onActivateNearMe"];
  onSelectAllSegment: MapCanvasProps["onSelectAllSegment"];
  onToggleSegment: MapCanvasProps["onToggleSegment"];
  onToggleAlerts: MapCanvasProps["onToggleAlerts"];
  onToggleNearMe: MapCanvasProps["onToggleNearMe"];
  onClearRisk: MapCanvasProps["onClearRisk"];
  onClearFilters: SelectedPlaceWorkspaceProps["onClearFilters"];
  onCyclePanelState: SelectedPlaceWorkspaceProps["onCyclePanelState"];
  onSheetPointerDown: SelectedPlaceWorkspaceProps["onSheetPointerDown"];
  onSheetPointerMove: SelectedPlaceWorkspaceProps["onSheetPointerMove"];
  onSheetPointerUp: SelectedPlaceWorkspaceProps["onSheetPointerUp"];
  onSheetPointerCancel: SelectedPlaceWorkspaceProps["onSheetPointerCancel"];
  onCloseFilterMode: SelectedPlaceWorkspaceProps["onCloseFilterMode"];
  onClosePlaceMode: SelectedPlaceWorkspaceProps["onClosePlaceMode"];
  onClearSampleDates: SelectedPlaceWorkspaceProps["onClearSampleDates"];
  onClearNearMe: SelectedPlaceWorkspaceProps["onClearNearMe"];
  onChipPointerDown: MapCanvasProps["onChipPointerDown"];
  onChipPointerMove: MapCanvasProps["onChipPointerMove"];
  onChipPointerUp: MapCanvasProps["onChipPointerUp"];
  onChipClickCapture: MapCanvasProps["onChipClickCapture"];
};
