"use client";

import type { DashboardTopChromeProps } from "./dashboard-controller-component-props";
import type { TopChromeInput } from "./dashboard-controller-top-chrome-types";

export function buildDashboardTopChromeProps(
  input: TopChromeInput,
): Omit<DashboardTopChromeProps, "langMenuRef"> {
  return {
    lang: input.lang,
    t: input.t,
    isMobile: input.isMobile,
    drawerOpen: input.drawerOpen,
    headerCompact: input.headerCompact,
    showLangDialog: input.showLangDialog,
    langMenuOpen: input.langMenuOpen,
    sidebarCollapsed: input.sidebarCollapsed,
    nearbyOnly: input.nearbyOnly,
    nearbyRadiusKm: input.nearbyRadiusKm,
    userCoords: input.userCoords,
    geoError: input.geoError,
    query: input.query,
    cyrillicFont: input.cyrillicFont,
    segment: input.segment,
    alertsOnly: input.alertsOnly,
    county: input.county,
    risk: input.risk,
    official: input.official,
    minProb: input.minProb,
    minProbInput: input.minProbInput,
    sampleDateFrom: input.sampleDateFrom,
    sampleDateTo: input.sampleDateTo,
    filteredCount: input.filteredCount,
    mapAlertsCount: input.mapAlertsCount,
    mapNearMeCount: input.mapNearMeCount,
    highRiskCount: input.highRiskCount,
    violationsCount: input.violationsCount,
    healthIndex: input.healthIndex,
    domainCounts: input.domainCounts,
    placeKinds: input.placeKinds,
    counties: input.counties,
    watchlistPlaces: input.watchlistPlaces,
    onCloseDrawer: input.onCloseDrawer,
    onOpenAboutModel: input.onOpenAboutModel,
    onChooseLang: input.onChooseLang,
    onToggleLangMenu: input.onToggleLangMenu,
    onSelectLangOption: input.onSelectLangOption,
    onOpenFilters: input.onOpenFilters,
    onSetQuery: input.onSetQuery,
    onActivateNearMe: input.onActivateNearMe,
    onOpenInfo: input.onOpenInfo,
    onSetSegment: input.onSetSegment,
    onToggleAlertsOnly: input.onToggleAlertsOnly,
    onToggleNearbyOnly: input.onToggleNearbyOnly,
    onClearRisk: input.onClearRisk,
    onClearFilters: input.onClearFilters,
    onShowCountBubble: input.onShowCountBubble,
    onClearGeoError: input.onClearGeoError,
    onToggleSidebar: input.onToggleSidebar,
    onSetNearbyRadiusKm: input.onSetNearbyRadiusKm,
    onClearNearMe: input.onClearNearMe,
    onSetLang: input.onSetLang,
    onPushHeaderLang: input.onPushHeaderLang,
    onSetCyrillicFont: input.onSetCyrillicFont,
    onSetCounty: input.onSetCounty,
    onSetRisk: input.onSetRisk,
    onSetOfficial: input.onSetOfficial,
    onSetMinProbInput: input.onSetMinProbInput,
    onSetSampleDateFrom: input.onSetSampleDateFrom,
    onSetSampleDateTo: input.onSetSampleDateTo,
    onSelectPoint: input.onSelectPoint,
    placeKindLabel: input.placeKindLabel,
    riskLabel: input.riskLabel,
    officialLabel: input.officialLabel,
  };
}
