"use client";

import type { ComponentProps, RefObject } from "react";
import type DashboardInsightsSection from "../components/DashboardInsightsSection";
import type DashboardMapWorkspace from "../components/DashboardMapWorkspace";
import type { DashboardFreshnessLevel, DashboardLang } from "./dashboard-types";
import type { FrontendSnapshot } from "./types";

type WorkspaceProps = ComponentProps<typeof DashboardMapWorkspace>;
type InsightsProps = ComponentProps<typeof DashboardInsightsSection>;

export type DashboardMainContentComponentProps = {
  lang: DashboardLang;
  snapshot: FrontendSnapshot;
  mapPanelRef: WorkspaceProps["mapPanelRef"];
  desktopDetailRef: RefObject<HTMLDivElement | null>;
  chipBarRef: WorkspaceProps["chipBarRef"];
  isMapFullscreen: WorkspaceProps["isMapFullscreen"];
  isMobile: boolean;
  chipPos: WorkspaceProps["chipPos"];
  segment: WorkspaceProps["segment"];
  alertsOnly: WorkspaceProps["alertsOnly"];
  nearbyOnly: WorkspaceProps["nearbyOnly"];
  risk: WorkspaceProps["risk"];
  county: WorkspaceProps["county"];
  official: WorkspaceProps["official"];
  minProb: WorkspaceProps["minProb"];
  minProbInput: WorkspaceProps["minProbInput"];
  sampleDateFrom: WorkspaceProps["sampleDateFrom"];
  sampleDateTo: WorkspaceProps["sampleDateTo"];
  nearbyRadiusKm: WorkspaceProps["nearbyRadiusKm"];
  userCoords: WorkspaceProps["userCoords"];
  geoError: WorkspaceProps["geoError"];
  theme: WorkspaceProps["theme"];
  selectedId: InsightsProps["selectedId"];
  selectedPlace: WorkspaceProps["selectedPlace"];
  clusterPlaces: WorkspaceProps["clusterPlaces"];
  watchlist: InsightsProps["watchlist"];
  measurementsOpen: WorkspaceProps["measurementsOpen"];
  historyOpen: WorkspaceProps["historyOpen"];
  mobilePanelState: WorkspaceProps["mobilePanelState"];
  sheetMode: WorkspaceProps["sheetMode"];
  sheetDragging: WorkspaceProps["sheetDragging"];
  sheetDragOffset: WorkspaceProps["sheetDragOffset"];
  filteredCount: number;
  highCount: WorkspaceProps["highCount"];
  lowCount: WorkspaceProps["lowCount"];
  violationsCount: WorkspaceProps["violationsCount"];
  mobileBottomOverlayPx: WorkspaceProps["mobileBottomOverlayPx"];
  counties: WorkspaceProps["counties"];
  countyGeoJson: WorkspaceProps["countyGeoJson"];
  fitBoundsKey: WorkspaceProps["fitBoundsKey"];
  mapPlaces: WorkspaceProps["mapPlaces"];
  fitBoundsPlaces: WorkspaceProps["fitBoundsPlaces"];
  placesTableRows: InsightsProps["placesTableRows"];
  placesTableSort: InsightsProps["placesTableSort"];
  topAlerts: InsightsProps["topAlerts"];
  domainStats: InsightsProps["domainStats"];
  dataFetchedLabel: WorkspaceProps["dataFetchedLabel"];
  modelTrainedLabel: WorkspaceProps["modelTrainedLabel"];
  dataFreshnessLevel: DashboardFreshnessLevel;
  modelFreshnessLevel: DashboardFreshnessLevel;
  freshnessLabel: WorkspaceProps["freshnessLabel"];
  title: WorkspaceProps["title"];
  filtersLabel: WorkspaceProps["filtersLabel"];
  clearFiltersLabel: WorkspaceProps["clearFiltersLabel"];
  nearMeLabel: WorkspaceProps["nearMeLabel"];
  selectedPointTitle: WorkspaceProps["selectedPointTitle"];
  emptySelectedPointHint: WorkspaceProps["emptySelectedPointHint"];
  measurementsLabel: WorkspaceProps["measurementsLabel"];
  historyLabel: WorkspaceProps["historyLabel"];
  historyPlaceholder: WorkspaceProps["historyPlaceholder"];
  closeLabel: WorkspaceProps["closeLabel"];
  countyLabel: WorkspaceProps["countyLabel"];
  riskLabelText: WorkspaceProps["riskLabelText"];
  officialLabelText: WorkspaceProps["officialLabelText"];
  minProbLabel: WorkspaceProps["minProbLabel"];
  latestSampleDateLabel: WorkspaceProps["latestSampleDateLabel"];
  dateFromLabel: WorkspaceProps["dateFromLabel"];
  dateToLabel: WorkspaceProps["dateToLabel"];
  resetDateLabel: WorkspaceProps["resetDateLabel"];
  latestSampleDateHint: WorkspaceProps["latestSampleDateHint"];
  nearRadiusLabel: WorkspaceProps["nearRadiusLabel"];
  clearNearMeLabel: WorkspaceProps["clearNearMeLabel"];
  placeKindLabel: WorkspaceProps["placeKindLabel"];
  countyPretty: WorkspaceProps["countyPretty"];
  officialStatusText: WorkspaceProps["officialStatusText"];
  explainViolation: WorkspaceProps["explainViolation"];
  explainMeasurementNorm: WorkspaceProps["explainMeasurementNorm"];
  explainHistoryMeasurements: WorkspaceProps["explainHistoryMeasurements"];
  explainViolationFromHistory: WorkspaceProps["explainViolationFromHistory"];
  labelForParam: WorkspaceProps["labelForParam"];
  descForParam: WorkspaceProps["descForParam"];
  openInfo: WorkspaceProps["openInfo"];
  onSelectPoint: (id: string) => void;
  onSelectCluster: WorkspaceProps["onSelectCluster"];
  onSelectCounty: WorkspaceProps["onSelectCounty"];
  onToggleWatch: (id: string) => void;
  onCycleSort: InsightsProps["onCycleSort"];
  onToggleMeasurements: WorkspaceProps["onToggleMeasurements"];
  onToggleHistory: WorkspaceProps["onToggleHistory"];
  onSetCounty: WorkspaceProps["onSetCounty"];
  onSetRisk: WorkspaceProps["onSetRisk"];
  onSetOfficial: WorkspaceProps["onSetOfficial"];
  onSetMinProbInput: WorkspaceProps["onSetMinProbInput"];
  onSetSampleDateFrom: WorkspaceProps["onSetSampleDateFrom"];
  onSetSampleDateTo: WorkspaceProps["onSetSampleDateTo"];
  onSetNearbyRadiusKm: WorkspaceProps["onSetNearbyRadiusKm"];
  onSetTheme: WorkspaceProps["onSetTheme"];
  onSetLang: WorkspaceProps["onSetLang"];
  onToggleFullscreen: WorkspaceProps["onToggleFullscreen"];
  onActivateNearMe: WorkspaceProps["onActivateNearMe"];
  onSelectAllSegment: WorkspaceProps["onSelectAllSegment"];
  onToggleSegment: WorkspaceProps["onToggleSegment"];
  onToggleAlerts: WorkspaceProps["onToggleAlerts"];
  onToggleNearMe: WorkspaceProps["onToggleNearMe"];
  onClearRisk: WorkspaceProps["onClearRisk"];
  onClearFilters: WorkspaceProps["onClearFilters"];
  onCyclePanelState: WorkspaceProps["onCyclePanelState"];
  onSheetPointerDown: WorkspaceProps["onSheetPointerDown"];
  onSheetPointerMove: WorkspaceProps["onSheetPointerMove"];
  onSheetPointerUp: WorkspaceProps["onSheetPointerUp"];
  onSheetPointerCancel: WorkspaceProps["onSheetPointerCancel"];
  onCloseFilterMode: WorkspaceProps["onCloseFilterMode"];
  onClosePlaceMode: WorkspaceProps["onClosePlaceMode"];
  onClearSampleDates: WorkspaceProps["onClearSampleDates"];
  onClearNearMe: WorkspaceProps["onClearNearMe"];
  onChipPointerDown: WorkspaceProps["onChipPointerDown"];
  onChipPointerMove: WorkspaceProps["onChipPointerMove"];
  onChipPointerUp: WorkspaceProps["onChipPointerUp"];
  onChipClickCapture: WorkspaceProps["onChipClickCapture"];
};
