import { SITE_ORIGIN } from "./site-metadata";

// Lightweight per-place metadata used by generateMetadata() to build
// per-location social previews. The index is generated by
// citizen-service/scripts/build_citizen_snapshot.py and served as a static
// file from /data/og-index.json. We fetch it at the edge with a long cache
// — same-origin, so Cloudflare's tiered cache keeps it ~free.

export type OgIndexEntry = {
  name: string;
  county: string | null;
  risk_level: "low" | "medium" | "high" | "unknown";
  status: "compliant" | "violation" | "unknown";
};

export type OgIndex = {
  places: Record<string, OgIndexEntry>;
};

const OG_WORKER_BASE = process.env.NEXT_PUBLIC_OG_WORKER_URL || "https://og.h2oatlas.ee";
// Where generateMetadata() / sitemap() fetch og-index.json from. Override
// via env when dev-ing locally before the first prod deploy populates the
// file at https://h2oatlas.ee/data/og-index.json. Example:
//   OG_INDEX_FETCH_BASE=http://localhost:3010 npm run dev
const OG_INDEX_FETCH_BASE = process.env.OG_INDEX_FETCH_BASE || SITE_ORIGIN;

export async function loadOgIndex(): Promise<OgIndex> {
  try {
    const version = process.env.NEXT_PUBLIC_SNAPSHOT_VERSION || "dev";
    const res = await fetch(`${OG_INDEX_FETCH_BASE}/data/og-index.json?v=${version}`, {
      next: { revalidate: 3600 },
    });
    if (!res.ok) return { places: {} };
    const json = (await res.json()) as Partial<OgIndex>;
    return { places: json.places ?? {} };
  } catch {
    return { places: {} };
  }
}

export function buildOgImageUrl(placeId: string | null): string {
  const version = process.env.NEXT_PUBLIC_SNAPSHOT_VERSION || "dev";
  if (!placeId) return `${SITE_ORIGIN}/og-default.png`;
  return `${OG_WORKER_BASE}/og?place=${encodeURIComponent(placeId)}&v=${encodeURIComponent(version)}`;
}
