"use client";

import { useDashboardControllerCollectionsRuntime } from "./use-dashboard-controller-collections-runtime";
import { useDashboardControllerInteractionRuntime } from "./use-dashboard-controller-interaction-runtime";
import { buildDashboardControllerRuntimeOutput } from "./dashboard-controller-runtime-output";
import { useDashboardControllerSceneState } from "./use-dashboard-controller-scene-state";
import { useDashboardControllerBootstrap } from "./use-dashboard-controller-bootstrap";
import type { FrontendSnapshot } from "./types";

type BootstrapState = ReturnType<typeof useDashboardControllerBootstrap>;

export function useDashboardControllerRuntime(snapshot: FrontendSnapshot, state: BootstrapState) {
  const scene = useDashboardControllerSceneState(snapshot, state);
  const {
    historyMeasurements,
    expertModeText,
    labelForParam,
    descForParam,
    explainMeasurementNorm,
    explainViolation,
    explainHistoryMeasurements,
    severityLabel,
    officialStatusText,
    placeKindLabel,
    riskLabel,
    officialLabel,
    openInfo,
    dataFetchedLabel,
    modelTrainedLabel,
    dataFreshness,
    modelFreshness,
    freshnessLabel,
    toast,
    freshnessBubble,
    pushHeaderLang,
    chooseLang,
    toggleWatch,
    clearFilters,
    selectPoint,
    handleClusterSelect,
    openFilters,
    toggleNearbyOnly,
    openAboutModel,
    openAboutService,
    toggleLangMenu,
    selectLangOption,
    toggleSidebar,
    clearNearMe,
    clearGeoError,
    clearSampleDates,
    setMobileSheetLang,
    explainViolationFromHistory,
    setMobileSheetTheme,
  } = useDashboardControllerInteractionRuntime(snapshot, state, scene);
  const {
    counties,
    placeKinds,
    domainCounts,
    parameterCards,
    handleCountySelect,
    filtered,
    placesTableRows,
    mapPlaces,
    mapAlertsCount,
    mapNearMeCount,
    fitBoundsKey,
    fitBoundsPlaces,
    countBubble,
    showCountBubble,
    activateNearMe,
    toggleMapFullscreen,
    selectAllSegment,
    toggleSegment,
    toggleAlerts,
    toggleNearMe,
    toggleMeasurements,
    toggleHistory,
    closeFilterMode,
    closePlaceMode,
    low,
    high,
    violations,
    healthIndex,
    domainStats,
    topAlerts,
    quickInsights,
  } = useDashboardControllerCollectionsRuntime(snapshot, state, scene, {
    pushHeaderLang,
    dataFreshnessLevel: dataFreshness.level,
    modelFreshnessLevel: modelFreshness.level,
  });

  return buildDashboardControllerRuntimeOutput({
    historyMeasurements,
    selectedPlace: scene.selectedPlace,
    clusterPlaces: scene.clusterPlaces,
    watchlistPlaces: scene.watchlistPlaces,
    mobilePanelState: scene.mobilePanelState,
    setMobilePanelState: scene.setMobilePanelState,
    sheetMode: scene.sheetMode,
    setSheetMode: scene.setSheetMode,
    sheetDragging: scene.sheetDragging,
    sheetDragOffset: scene.sheetDragOffset,
    cycleMobilePanelState: scene.cycleMobilePanelState,
    onSheetPointerDown: scene.onSheetPointerDown,
    onSheetPointerMove: scene.onSheetPointerMove,
    onSheetPointerUp: scene.onSheetPointerUp,
    resetSheetDrag: scene.resetSheetDrag,
    chipPos: scene.chipPos,
    onChipPointerDown: scene.onChipPointerDown,
    onChipPointerMove: scene.onChipPointerMove,
    onChipPointerUp: scene.onChipPointerUp,
    onChipClick: scene.onChipClick,
    isMobile: scene.isMobile,
    countyGeoJson: scene.countyGeoJson,
    mobileBottomOverlayPx: scene.mobileBottomOverlayPx,
    expertModeText,
    labelForParam,
    descForParam,
    explainMeasurementNorm,
    explainViolation,
    explainHistoryMeasurements,
    severityLabel,
    officialStatusText,
    placeKindLabel,
    riskLabel,
    officialLabel,
    openInfo,
    dataFetchedLabel,
    modelTrainedLabel,
    dataFreshness,
    modelFreshness,
    freshnessLabel,
    pushHeaderLang,
    chooseLang,
    toggleWatch,
    clearFilters,
    selectPoint,
    handleClusterSelect,
    openFilters,
    toggleNearbyOnly,
    toast,
    freshnessBubble,
    counties,
    placeKinds,
    domainCounts,
    parameterCards,
    handleCountySelect,
    openAboutModel,
    openAboutService,
    toggleLangMenu,
    selectLangOption,
    toggleSidebar,
    clearNearMe,
    clearGeoError,
    clearSampleDates,
    setMobileSheetLang,
    explainViolationFromHistory,
    setMobileSheetTheme,
    filtered,
    placesTableRows,
    mapPlaces,
    mapAlertsCount,
    mapNearMeCount,
    fitBoundsKey,
    fitBoundsPlaces,
    countBubble,
    showCountBubble,
    activateNearMe,
    toggleMapFullscreen,
    selectAllSegment,
    toggleSegment,
    toggleAlerts,
    toggleNearMe,
    toggleMeasurements,
    toggleHistory,
    closeFilterMode,
    closePlaceMode,
    low,
    high,
    violations,
    healthIndex,
    domainStats,
    topAlerts,
    quickInsights,
  });
}
